---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/observability/vm-agent

patches:
  - target:
      kind: VMAgent
      name: vmagent
    patch: |-
      - op: replace
        path: /spec/externalLabels/cluster
        value: rmz3
