---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./victoria-metrics-rbac.yaml
  - ./victoria-metrics-agent.yaml
  - ./victoria-metrics-nodescrape.yaml
  - ./victoria-metrics-cadvisor-nodescrape.yaml
  - ./victoria-metrics-nodeproblem-scrape.yaml
