---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openstack

resources:
  - ./namespace.yaml

secretGenerator:
  - name: mariadb-root-password
    options:
      disableNameSuffixHash: true
    literals:
      - password=tgYEKpeVcfYXGKCxyY5WNM7WHLotRDWN

  - name: keystone-db-password
    options:
      disableNameSuffixHash: true
    literals:
      - password=UbhD654k4qqrggW5DQFynWU44cuNrpEe

  - name: keystone-rabbitmq-password
    options:
      disableNameSuffixHash: true
    literals:
      - username=keystone
      - password=nxBKqcJMnEqoNJ7TEkWj4Ly6oqip5QW4

  - name: glance-db-password
    options:
      disableNameSuffixHash: true
    literals:
      - password=DriKdoSFyRE2pbeYRbkq2rTTe8ZGv8Cb

  - name: glance-rabbitmq-password
    options:
      disableNameSuffixHash: true
    literals:
      - username=glance
      - password=RxkDJHpN7BeUQKAZqEN5ruqJxSMLgkCu

  - name: cinder-db-password
    options:
      disableNameSuffixHash: true
    literals:
      - password=W8CnENzMZB6l2f1iDM2V1MqqGzJN0YzF

  - name: cinder-rabbitmq-password
    options:
      disableNameSuffixHash: true
    literals:
      - username=cinder
      - password=fK9028i3TsoyT0iBxmFFSHTIF5PHPI45

  - name: cinder-keystone-password
    options:
      disableNameSuffixHash: true
    literals:
      - password=26l0XbK17LrlbntxUT35GC3hrBOUZ93B
