---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openstack

resources:
  - ./namespace.yaml

secretGenerator:
  - name: mariadb-root-password
    options:
      disableNameSuffixHash: true
    literals:
      - password=ZNfM46C8n9mKdaqPYpgFzQe7u5UDGvkV

  - name: keystone-db-password
    options:
      disableNameSuffixHash: true
    literals:
      - password=BHJMDNaj57ZQhxn2vbLFR3Pt4cz9wTeg

  - name: keystone-rabbitmq-password
    options:
      disableNameSuffixHash: true
    literals:
      - username=keystone
      - password=BnPfUNyb5X9gvWMxYwEHjSDA3LkGsTFK

  - name: glance-db-password
    options:
      disableNameSuffixHash: true
    literals:
      - password=q3JfCuAhLDBXP9YSz5n26HMWrKedjFck

  - name: glance-rabbitmq-password
    options:
      disableNameSuffixHash: true
    literals:
      - username=glance
      - password=nR7u3czq28fCr49PswTydMYXaGZEktgj

  - name: cinder-db-password
    options:
      disableNameSuffixHash: true
    literals:
      - password=rbeExagp6NXmkBGCw3f7yYL2H5J4ucsq

  - name: cinder-rabbitmq-password
    options:
      disableNameSuffixHash: true
    literals:
      - username=cinder
      - password=X27cBJhRM6DAgnbLZUwF48aSxTNmGzfr

  - name: cinder-keystone-password
    options:
      disableNameSuffixHash: true
    literals:
      - password=kHfDdFzEQKNcqb38suaUChVSr2v6JMWT

  - name: placement-db-password
    options:
      disableNameSuffixHash: true
    literals:
      - password=y95D7JTRUfwuN8zSKmEvd3ZPrVqCY2be

  - name: neutron-db-password
    options:
      disableNameSuffixHash: true
    literals:
      - password=RnYVpkmMJjBxa8GerS5TbuE9wUCL6XQc

  - name: neutron-rabbitmq-password
    options:
      disableNameSuffixHash: true
    literals:
      - username=neutron
      - password=JwPk2sDWbua4mEpjf6t8nNeqd7KZGxUB

  - name: nova-db-password
    options:
      disableNameSuffixHash: true
    literals:
      - password=sCpkHdhNZTELjV65uQ94SfqtanDWr3Rw

  - name: nova-rabbitmq-password
    options:
      disableNameSuffixHash: true
    literals:
      - username=nova
      - password=Lr5Zga8QJ9vjD6t3fEMCnysTFzHu7em4

  - name: horizon-db-password
    options:
      disableNameSuffixHash: true
    literals:
      - password=XGNm7hV8P6vRFDk9LfwEezutqyK4gsZn
