apiVersion: k8s.mariadb.com/v1alpha1
kind: PhysicalBackup
metadata:
  name: physicalbackup
spec:
  mariaDbRef:
    name: mariadb
  schedule:
    cron: "0 */6 * * *"
    immediate: true
  compression: bzip2
  maxRetention: 48h
  storage:
    s3:
      bucket: openstack-backups
      prefix: mariadb
      endpoint: http://100.100.171.15:9000
      region: us-east-1
      accessKeyIdSecretKeyRef:
        name: s3-creds
        key: access-key-id
      secretAccessKeySecretKeyRef:
        name: s3-creds
        key: secret-access-key
