release_group: glance

bootstrap:
  enabled: true
  ks_user: admin
  script:
  structured:
    images: []

network:
  api:
    ingress:
      public: false

conf:
  glance:
    DEFAULT:
      workers: 4
  glance_api_uwsgi:
    uwsgi:
      add-header: "Connection: close"
      buffer-size: 65535
      die-on-term: true
      enable-threads: true
      exit-on-reload: false
      hook-master-start: unix_signal:15 gracefully_kill_them_all
      lazy-apps: true
      log-x-forwarded-for: true
      master: true
      procname-prefix-spaced: "glance-api:"
      route-user-agent: "^kube-probe.* donotlog:"
      thunder-lock: true
      worker-reload-mercy: 80
      module: glance.wsgi.api:application
      stats: 0.0.0.0:1717
      stats-http: true
      http-timeout: 600
      socket-timeout: 600
      harakiri: 600

volume:
  class_name: "local-path"
  size: "10Gi"
  accessModes:
    - "ReadWriteOnce"

volume_staging:
  class_name: "local-path"
  size: 10Gi
  accessModes:
    - ReadWriteOnce

pod:
  replicas:
    api: 1
  resources:
    enabled: true
    api:
      requests:
        memory: "512Mi"
        cpu: "1000m"
      limits:
        memory: "2048Mi"
        cpu: "2000m"

dependencies:
  dynamic:
    common:
      local_image_registry:
        jobs:
  static:
    db_sync:
      jobs:
    api:
      jobs:
        - glance-db-sync
        - glance-ks-user
        - glance-ks-endpoints

manifests:
  certificates: false
  configmap_bin: true
  configmap_etc: true
  deployment_api: true
  ingress_api: true
  job_bootstrap: true
  job_clean: true
  job_db_init: false
  job_db_sync: true
  job_db_drop: false
  job_image_repo_sync: true
  job_ks_endpoints: true
  job_ks_service: true
  job_ks_user: true
  job_storage_init: true
  job_metadefs_load: true
  job_rabbit_init: false
  pdb_api: true
  pod_rally_test: false
  pvc_images: true
  network_policy: false
  secret_db: false
  secret_ingress_tls: false
  secret_keystone: true
  secret_rabbitmq: false
  secret_registry: true
  service_ingress_api: true
  service_api: true
