apiVersion: k8s.mariadb.com/v1alpha1
kind: PhysicalBackup
metadata:
  name: physicalbackup
spec:
  mariaDbRef:
    name: mariadb
  storage:
    persistentVolumeClaim:
      accessModes:
        - ReadWriteOnce
      storageClassName: "local-path"
      resources:
        requests:
          size: 10G
  schedule:
    cron: "0 */6 * * *"
    immediate: true
  compression: bzip2
  maxRetention: 48h
