---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cnpg-operator
  namespace: flux-system
  labels:
    openstack-helm-flux/component-group: operators
spec:
  interval: 60m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: openstack-helm-flux-repo
    namespace: flux-system
  path: ./sites/rmz2/infrastructure/cnpg-operator
  prune: true
  wait: true
  force: true
