---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openstack-glance-values
  namespace: openstack
  labels:
    openstack-helm-flux/component-group: openstack
spec:
  interval: 30m
  targetNamespace: openstack
  dependsOn:
    - name: openstack-common-values
    - name: openstack-rabbitmq
    - name: openstack-mariadb
  sourceRef:
    kind: GitRepository
    name: openstack-helm-flux-repo
    namespace: flux-system
  path: ./sites/rmz2/openstack-apps/openstack-glance
  prune: true
  wait: true

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openstack-glance
  namespace: openstack
  labels:
    openstack-helm-flux/component-group: openstack
spec:
  interval: 10m
  targetNamespace: openstack
  releaseName: glance
  timeout: 30m
  dependsOn:
    - name: infra-envoy-gateway
    - name: openstack-memcached
    - name: openstack-keystone
  chart:
    spec:
      chart: glance
      version: 2026.1.5+a2a343968
      sourceRef:
        kind: HelmRepository
        name: openstack-helm-repo
        namespace: flux-system
  install:
    timeout: 30m
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    timeout: 45m
    disableWait: true
    disableWaitForJobs: true
    force: true
  valuesFrom:
    - kind: ConfigMap
      name: openstack-common-endpoints
      valuesKey: values.yaml
    - kind: ConfigMap
      name: openstack-helm-flux-glance-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: openstack-helm-flux-glance-values-override
      valuesKey: values.yaml
    - kind: Secret
      name: glance-db-password
      valuesKey: password
      targetPath: endpoints.oslo_db.auth.glance.password
    - kind: Secret
      name: glance-rabbitmq-password
      valuesKey: password
      targetPath: endpoints.oslo_messaging.auth.glance.password
