---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openstack-mariadb
  namespace: openstack
  labels:
    openstack-helm-flux/component-group: openstack-infra
spec:
  interval: 30m
  timeout: 30m
  targetNamespace: openstack
  dependsOn:
    - name: infra-local-path-provisioner
  sourceRef:
    kind: GitRepository
    name: openstack-helm-flux-repo
    namespace: flux-system
  path: ./sites/rmz2/openstack-apps/mariadb-cluster
  prune: true
  wait: true
  force: true
  healthChecks:
    - name: mariadb
      kind: StatefulSet
      apiVersion: apps/v1
  healthCheckExprs:
    - apiVersion: k8s.mariadb.com/v1alpha1
      kind: MariaDB
      current: >-
        has(status.conditions) &&
        status.conditions.exists(c, c.type == 'Ready' && c.status == 'True')
