---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespaces.yaml
  - ./flux/sources.yaml
  - ./flux/infra-local-path-provisioner.yaml
  - ./flux/infra-cnpg-operator.yaml
  - ./flux/infra-rabbitmq-cluster-operator.yaml
  - ./flux/infra-rabbitmq-topology-operator.yaml
  - ./flux/infra-mariadb-crds.yaml
  - ./flux/infra-mariadb-operator.yaml
  - ./flux/infra-envoy-gateway.yaml
  - ./flux/openstack-memcached.yaml
  - ./flux/openstack-rabbitmq.yaml
  - ./flux/openstack-nova-rabbitmq.yaml
  - ./flux/openstack-mariadb.yaml
  - ./flux/openstack-common.yaml
  - ./flux/openstack-keystone.yaml
  - ./flux/openstack-glance.yaml
  - ./flux/openstack-cinder.yaml
  - ./flux/openstack-libvirt.yaml
  - ./flux/openstack-openvswitch.yaml
  - ./flux/openstack-ovn.yaml
